### ISSUE TITLE
compiles on VS2022 but crashes

### ISSUE THREAD

**Issue by lonnietc** [carloshgsilva/VoxelEngine#1]
Hello,

I followed your steps and tried to compile and run it on my Visual Studio 2022 but it seems to crash as soon as it tries to start up.

Do you have a standard solution file instead of one created with cmake instead?

Also, would it be possible for you to put up a zipped set of binaries in your release section on Github just so that I can download and test it out on my Windows 10 (x64)?

Thanks

**Comment by lonnietc** [comment]
I was able to get the code to compile in "Release" and even start up, but it does not function as in your image on the Github site:

Here is what I get:

![image](https://user-images.githubusercontent.com/15264930/223765700-2b08449c-ba4a-4ad2-b4fc-c8153588cb31.png)

But none of the items seem to work at all.

**Comment by lonnietc** [comment]
Also, I have:

Windows 10 (x64)
VulkanSDK-1.3.239.0
Visual Studio 2022  

I am basically just trying to replicate what you show in the Github page image as a first step to ensure that everything compiles and run correctly which is why I was also asking if you had a standard VS solution file already along with pre-compiled binaries that I can run as well.

Thanks and look forward to hearing from you.

**Comment by carloshgsilva** [comment]
Hi @lonnietc,

The binary release should be working fine as in your image, it seems that the ImGui window layout is just not organized. Try to expand the small window, it should be the viewport.

For build I would like to only maintain the CMake project.

I will also not maintain the main branch anymore and it will be replaced by the raytracing branch where it's mandatory to have a GPU that supports raytracing, but that branch is far from ready and probably won't build out of the box for now.

**Comment by lonnietc** [comment]
@carloshgsilva Thanks getting back to me on this and I was able to expand things to get a bit of interaction.

I it seems that it has good potential but I did not see it in simple ways to add voxels but it does allow you to select "objects" and such which is nice.

Guess that I was thinking that it would be more like a typical "minecraft" type voxel engine in which you add voxels one-by-one  although I will explore it more.

I did find that when I enlarge the view window and then grab an object to move or scale that the interface also seems to move the actual ImGui window as well working on the object. The ImGui window does not anchor in place .  Also, the top bar with file, edit, tools, etc. does not have any functionality or sub-menu actions.

Lastly, I would be really interested in seeing your new raytrace branch and if you would like a beta-tester then please let me know as I had thought about building a voxel-ray-trace vulkan engine (possibly using Methane https://github.com/MethanePowered/MethaneKit or Diligent Engine https://github.com/DiligentGraphics/DiligentEngine) since they are cross-platform as well.

**Comment by carloshgsilva** [comment]
@lonnietc yeah, lots of missing features and lots of bugs.

An voxel editor would be something interesting to build, it's just that I've never really settled on which rendering technique to use and didn't dive into this adventure yet.

This was an engine I built to learn the whole process, if I were to rebuild everything again I would do lots of things differently.
I will keep updating the raytracing branch and do the changes I think is better.

I don't really want to use other engine since I want to learn as much as possible building my own.

I also work so I will just update it on my free time, if you want you can follow my updates on [Twitter](https://twitter.com/HenriqueGoisDev).

**Comment by lonnietc** [comment]
@carloshgsilva Hope that your weekend is going well.

I just looked over your Twitter page and I really like the PathTracer video 

https://www.youtube.com/watch?v=Wiaj54mUDCY

On that note, I am really seeking to possible build up a good Voxel 3D engine that has some exciting features and very unique features and would really like to discuss them more with you to see if we might be able to collaborate or possibly team up in some way to build out a remarkable engine that can compete with Atomontage

https://www.atomontage.com/

Maybe you could reach out to me at Lonnie@outstep.com and we could discuss what I had in mind and see if there is something that we can do together. Will look forward to hearing from you soon, my friend.

Best Regards and have a great day
